database:
  host: postgres   # имя сервиса в docker-compose
  port: 5432
  user: postgres
  password: mysecretpassword
  dbname: deadline_service_db
  sslmode: disable

worker:
  interval_seconds: 60
